[pytest]
markers =
    core: All tests for the core logic layer
    ui: All UI tests
    assets: Tests for AssetManager
    renderer: Tests for GameRenderer
    game: mark a test as related to the Game class.
    logic: mark a test as related to the EventHandler and logic.

pythonpath = .
